using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Booking_system
{
    public interface ILogable
    {
        // Provides uniqe ID (uniqe ID as a PESEL, not this generated by database).
        public string GetID();

        public string GetPassword();

        public bool Login(ILogable user);
    }
}
